CREATE TABLE "qatering-go_customer_address" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qatering-go_customer_address_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"recipient_name" text NOT NULL,
	"address_line1" text NOT NULL,
	"city" text NOT NULL,
	"postal_code" text NOT NULL,
	"delivery_instructions" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "qatering-go_menu_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qatering-go_menu_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vendor_id" integer NOT NULL,
	"item_name" text NOT NULL,
	"description" text,
	"unit_price" numeric(12, 2) NOT NULL,
	"is_available" boolean DEFAULT true NOT NULL,
	"image_url" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "qatering-go_order" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qatering-go_order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customer_id" text NOT NULL,
	"vendor_id" integer NOT NULL,
	"delivery_address_id" integer NOT NULL,
	"order_status" text DEFAULT 'pending' NOT NULL,
	"total_amount" numeric(12, 2) NOT NULL,
	"placed_at" timestamp DEFAULT now() NOT NULL,
	"required_delivery_time" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "qatering-go_order_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qatering-go_order_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"order_id" integer NOT NULL,
	"menu_item_id" integer NOT NULL,
	"quantity" integer NOT NULL,
	"unit_price_snapshot" numeric(12, 2) NOT NULL,
	"special_requests" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "qatering-go_payment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qatering-go_payment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"order_id" integer NOT NULL,
	"payment_method_id" integer NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"payment_status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "qatering-go_payment_order_id_unique" UNIQUE("order_id")
);
--> statement-breakpoint
CREATE TABLE "qatering-go_payment_cod_details" (
	"payment_id" integer PRIMARY KEY NOT NULL,
	"collected_by" text,
	"collected_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "qatering-go_payment_method" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qatering-go_payment_method_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"name" text NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "qatering-go_payment_method_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "qatering-go_payment_midtrans_details" (
	"payment_id" integer PRIMARY KEY NOT NULL,
	"midtrans_transaction_id" text,
	"midtrans_order_id" text,
	"gateway_status" text,
	"payment_type_used" text,
	"transaction_time" timestamp
);
--> statement-breakpoint
CREATE TABLE "qatering-go_vendor" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qatering-go_vendor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"business_name" text NOT NULL,
	"business_description" text,
	"support_phone" text,
	"status" text DEFAULT 'pending_approval' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "qatering-go_vendor_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "qatering-go_vendor_location" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qatering-go_vendor_location_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vendor_id" integer NOT NULL,
	"address_line1" text NOT NULL,
	"city" text NOT NULL,
	"postal_code" text NOT NULL,
	"gps_latitude" text,
	"gps_longitude" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"role" text DEFAULT 'customer',
	"phone_number" integer NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email"),
	CONSTRAINT "user_phone_number_unique" UNIQUE("phone_number")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "qatering-go_customer_address" ADD CONSTRAINT "qatering-go_customer_address_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qatering-go_menu_item" ADD CONSTRAINT "qatering-go_menu_item_vendor_id_qatering-go_vendor_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."qatering-go_vendor"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qatering-go_order" ADD CONSTRAINT "qatering-go_order_customer_id_user_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qatering-go_order" ADD CONSTRAINT "qatering-go_order_vendor_id_qatering-go_vendor_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."qatering-go_vendor"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qatering-go_order" ADD CONSTRAINT "qatering-go_order_delivery_address_id_qatering-go_customer_address_id_fk" FOREIGN KEY ("delivery_address_id") REFERENCES "public"."qatering-go_customer_address"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qatering-go_order_item" ADD CONSTRAINT "qatering-go_order_item_order_id_qatering-go_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."qatering-go_order"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qatering-go_order_item" ADD CONSTRAINT "qatering-go_order_item_menu_item_id_qatering-go_menu_item_id_fk" FOREIGN KEY ("menu_item_id") REFERENCES "public"."qatering-go_menu_item"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qatering-go_payment" ADD CONSTRAINT "qatering-go_payment_order_id_qatering-go_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."qatering-go_order"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qatering-go_payment" ADD CONSTRAINT "qatering-go_payment_payment_method_id_qatering-go_payment_method_id_fk" FOREIGN KEY ("payment_method_id") REFERENCES "public"."qatering-go_payment_method"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qatering-go_payment_cod_details" ADD CONSTRAINT "qatering-go_payment_cod_details_payment_id_qatering-go_payment_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."qatering-go_payment"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qatering-go_payment_midtrans_details" ADD CONSTRAINT "qatering-go_payment_midtrans_details_payment_id_qatering-go_payment_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."qatering-go_payment"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qatering-go_vendor" ADD CONSTRAINT "qatering-go_vendor_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qatering-go_vendor_location" ADD CONSTRAINT "qatering-go_vendor_location_vendor_id_qatering-go_vendor_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."qatering-go_vendor"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "customerAddress_userId_idx" ON "qatering-go_customer_address" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "menuItem_vendorId_idx" ON "qatering-go_menu_item" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "menuItem_isAvailable_idx" ON "qatering-go_menu_item" USING btree ("is_available");--> statement-breakpoint
CREATE INDEX "order_customerId_idx" ON "qatering-go_order" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "order_vendorId_idx" ON "qatering-go_order" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "order_status_idx" ON "qatering-go_order" USING btree ("order_status");--> statement-breakpoint
CREATE INDEX "orderItem_orderId_idx" ON "qatering-go_order_item" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "orderItem_menuItemId_idx" ON "qatering-go_order_item" USING btree ("menu_item_id");--> statement-breakpoint
CREATE UNIQUE INDEX "payment_orderId_idx" ON "qatering-go_payment" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "payment_status_idx" ON "qatering-go_payment" USING btree ("payment_status");--> statement-breakpoint
CREATE UNIQUE INDEX "vendor_userId_idx" ON "qatering-go_vendor" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "vendor_status_idx" ON "qatering-go_vendor" USING btree ("status");--> statement-breakpoint
CREATE INDEX "vendorLocation_vendorId_idx" ON "qatering-go_vendor_location" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" USING btree ("identifier");