import "@/styles/globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Header } from "@/components/layout/header"
import { Toaster } from "@/components/ui/sonner"
import { TRPCReactProvider } from "@/trpc/react"

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter-sans",
})

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className={`${inter.variable}`} lang='en' suppressHydrationWarning>
      <body>
        <TRPCReactProvider>
          <div className='relative flex min-h-screen flex-col'>
            <Header />
            <main className='flex-1'>{children}</main>
            <Toaster richColors />
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
